### ISSUE TITLE
v0.10.0 onwards breaks rate limiting retries

### ISSUE THREAD

**Issue by durkode** [aio-libs/aiobotocore#698] opened 2019-05-05 23:55 UTC
**Describe the bug**

With v0.9.4, when a rate limiting error is received it backs off and retries again later. In v0.10.0 (and also observed with v0.10.2) this rate limiting error is thrown without retrying.

**Checklist**
- [x] I have reproduced in environment where `pip check` passes without errors
- [x] I have provided `pip freeze` results
- [x] I have provided sample code or detailed way to reproduce

**pip freeze results**

For v0.10.0 where broken:

```
aiobotocore==0.10.0
aiohttp==3.5.4
async-timeout==3.0.1
attrs==19.1.0
botocore==1.12.49
chardet==3.0.4
docutils==0.14
idna==2.8
jmespath==0.9.4
multidict==4.5.2
python-dateutil==2.8.0
six==1.12.0
urllib3==1.24.3
wrapt==1.11.1
yarl==1.3.0
```

For v0.9.4 where it works:

```
aiobotocore==0.9.4
aiohttp==3.5.4
async-timeout==3.0.1
attrs==19.1.0
botocore==1.10.58
chardet==3.0.4
docutils==0.14
idna==2.8
jmespath==0.9.4
multidict==4.5.2
python-dateutil==2.8.0
six==1.12.0
wrapt==1.11.1
yarl==1.3.0
```

**Environment:**
 - Python Version: 3.7.3
 - OS name and version: Ubuntu 16.04 (default Ubuntu provided AMI on AWS)

**Additional context**

To reproduce the issue I have the following script:

```
#!/usr/bin/env python3

import aiobotocore
import asyncio
import datetime
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)

async def get_target_groups(session: aiobotocore.session.AioSession, alb_arn: str):

  async with session.create_client('elbv2') as elbv2_client:
    result = await elbv2_client.describe_target_groups(LoadBalancerArn=alb_arn)
    return result

async def main():
  
  session = aiobotocore.get_session(loop=loop)
  role_arn = "arn:aws:iam::xxxxxxxxxxxx:role/admin"

  alb_arn = "arn:aws:elasticloadbalancing:us-east-1:xxxxxxxxxxxx:loadbalancer/app/dev-api/47ffab81ba732952"

  logging.info("Starting attempts")
  prev_time = datetime.datetime.now()
  for x in range(100):
    result = await get_target_groups(session=session, alb_arn=alb_arn)
    curr_time = datetime.datetime.now()
    logging.info(f"Attempt {x:03d} ran in {curr_time - prev_time}")
    prev_time = curr_time


if __name__ == "__main__":
  try:
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
  except Exception as e:
    logging.critical(e)
    raise

```

When running with 0.9.4 I get an output similar to the following

```
(testingold) ubuntu@ip-10-0-2-161:~$ ./tester.py
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
INFO:root:Starting attempts
INFO:root:Attempt 000 ran in 0:00:00.047349
INFO:root:Attempt 001 ran in 0:00:00.038979
INFO:root:Attempt 002 ran in 0:00:00.039862
...
INFO:root:Attempt 068 ran in 0:00:00.032086
INFO:root:Attempt 069 ran in 0:00:00.027376
INFO:root:Attempt 070 ran in 0:00:02.677946
INFO:root:Attempt 071 ran in 0:00:00.026220
INFO:root:Attempt 072 ran in 0:00:00.023132
...
INFO:root:Attempt 098 ran in 0:00:00.517366
INFO:root:Attempt 099 ran in 0:00:00.028416
```

Note attempt 70 hit the rate limit and hence backed off. I previously checked this actually was a retry to rate limiting by setting `boto3.set_stream_logger('botocore.retryhandler', logging.DEBUG)` however removed the boto3 dependency to simplify this bug report.

Then when running the same code with 0.10.0 I get

```
(testing) ubuntu@ip-10-0-2-161:~$ ./tester.py
INFO:root:Starting attempts
INFO:root:Attempt 000 ran in 0:00:00.050868
INFO:root:Attempt 001 ran in 0:00:00.040029
...
INFO:root:Attempt 085 ran in 0:00:00.029554
INFO:root:Attempt 086 ran in 0:00:00.029750
CRITICAL:root:An error occurred (Throttling) when calling the DescribeTargetGroups operation: Rate exceeded
Traceback (most recent call last):
  File "./tester.py", line 69, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "./tester.py", line 60, in main
    result = await get_target_groups(session=session, alb_arn=alb_arn)
  File "./tester.py", line 39, in get_target_groups
    result = await elbv2_client.describe_target_groups(LoadBalancerArn=alb_arn)
  File "/home/ubuntu/.virtualenvs/testing/lib/python3.7/site-packages/aiobotocore/client.py", line 105, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Throttling) when calling the DescribeTargetGroups operation: Rate exceeded
```

Setting max_attempts in client_config explicitly does not fix the issue.

This is a blocker for us to upgrade to v0.10.2 (which has some new enpoints in botocore we want to use). Hopefully someone with more expertise in this library has some clue as to why this error might be occurring. Let me know if there is any missing info that might be needed.

**Comment by thehesiod** [comment] 2019-05-09 04:28
thanks for report, will look into this asap

**Comment by thehesiod** [comment] 2019-05-09 05:30
this is a botocore bug, I just reproduced it with botocore: 

```python
#!/usr/bin/env python3

import aiobotocore
import botocore.session
import botocore.config
import asyncio
import logging
import sys
import concurrent.futures


logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logger = logging.getLogger()

ALB_ARN = ...

CONFIG = botocore.config.Config(max_pool_connections=100)


async def main():
    session = aiobotocore.get_session()

    async with session.create_client('elbv2', config=CONFIG) as elbv2_client:
        logging.info("Starting attempts")

        try:
            await asyncio.gather(*[elbv2_client.describe_target_groups(LoadBalancerArn=ALB_ARN) for _ in range(100)])
        except:
            logger.exception("Error occurred with aiobotocore, trying botocore...")
            smain()


def smain():
    session = botocore.session.Session()
    elbv2_client = session.create_client('elbv2', config=CONFIG)

    with concurrent.futures.ThreadPoolExecutor(100) as pool:
        for future in concurrent.futures.as_completed([pool.submit(elbv2_client.describe_target_groups, LoadBalancerArn=ALB_ARN) for _ in range(100)]):
            future.result()


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

The issue is that when you make an API call, if the error code is > 300, it will throw: https://github.com/boto/botocore/blob/develop/botocore/client.py#L658 but won't re-try: https://github.com/boto/botocore/blob/develop/botocore/client.py#L357

**Comment by thehesiod** [comment] 2019-05-09 05:30
can log it there

**Comment by thehesiod** [comment] 2019-05-13 19:30
closing as this isn't an aiobotocore issue.  Feel free to re-open if you don't feel this is the case!

**Closed by thehesiod** 2019-05-13 19:30 UTC
