### ISSUE TITLE
ImportError: cannot import name 'MultiDict'

### ISSUE THREAD

**Issue by jean553** [aio-libs/aiobotocore#138] opened 2017-03-20 21:46 UTC
Hi,

I get the following error when executing my service with Python 3.5.2:

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vagrant/aiohttp-s3-files-manager/aiohttp-s3-files-manager/__main__.py", line 8, in <module>
    from .handle_get_connectivity_status import handle_get_connectivity_status
  File "/home/vagrant/aiohttp-s3-files-manager/aiohttp-s3-files-manager/handle_get_connectivity_status.py", line 5, in <module>
    import aiobotocore
  File "/tmp/virtual_env35/lib/python3.5/site-packages/aiobotocore/__init__.py", line 1, in <module>
    from .session import get_session, AioSession
  File "/tmp/virtual_env35/lib/python3.5/site-packages/aiobotocore/session.py", line 7, in <module>
    from .client import AioClientCreator
  File "/tmp/virtual_env35/lib/python3.5/site-packages/aiobotocore/client.py", line 11, in <module>
    from .args import AioClientArgsCreator
  File "/tmp/virtual_env35/lib/python3.5/site-packages/aiobotocore/args.py", line 9, in <module>
    from .endpoint import AioEndpointCreator
  File "/tmp/virtual_env35/lib/python3.5/site-packages/aiobotocore/endpoint.py", line 14, in <module>
    from aiohttp import MultiDict
ImportError: cannot import name 'MultiDict'
```

I simply import aiobotocore and asyncio in my file `handle_get_connectivity_status.py`.

My libraries versions:
```
aiobotocore (0.2.2)
aiohttp (2.0.0)
appdirs (1.4.3)
async-timeout (1.2.0)
botocore (1.5.26)
chardet (2.3.0)
docutils (0.13.1)
jmespath (0.9.2)
multidict (2.1.4)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
python-dateutil (2.6.0)
setuptools (34.3.2)
six (1.10.0)
wheel (0.29.0)
yarl (0.10.0)
```

The requirements.txt I used to install my packages (as mentionned in the README.md of aiohttp and aiobotocore):
```
aiobotocore
aiohttp
async-timeout
chardet
multidict
yarl
botocore
```

Am I missing something or did I misundertand something ? ( I didn't get this problem before)
Thanks!

**Comment by jettify** [comment] 2017-03-20 23:42
Hi, most likely you are using new `aiohttp` https://github.com/aio-libs/aiohttp/releases/tag/2.0.0 (released today) it has a lot of new features (parser from nodejs) as well as backward incompatible changes. Fo now you can use aiohttp 1.3.x we will fix 2.0.x support soon.

**Comment by graingert** [comment] 2017-03-21 08:57
Duplicate of #137

**Comment by jettify** [comment] 2017-03-21 10:07
aiohttp version pined for now, feel free to reopen

**Closed by jettify** 2017-03-21 10:07 UTC

**Comment by jean553** [comment] 2017-03-21 12:37
Hi, it works by changing the aiohttp version. Will wait for this fix to be merged (https://github.com/aio-libs/aiobotocore/pull/135/files).  Thanks!
