### ISSUE TITLE
`endpoint.py` line 307: `TypeError: init() got an unexpected keyword argument 'verify_ssl'`

### ISSUE THREAD

**Issue by noahbenson** [aio-libs/aiobotocore#861] opened 2021-04-07 13:57 UTC
**Describe the bug**
I received [this bug report](https://github.com/noahbenson/neuropythy/issues/20) for a library I maintain that uses `s3fs`, which in its recent version uses `aiobotocore`. I have traced the error to what appears to be a clear problem in the source code: [this line](https://github.com/aio-libs/aiobotocore/blob/332ac8a33d40f6168a7fd86b34faa9b2798056f0/aiobotocore/endpoint.py#L307-L311) passes the keyword argument `verify_ssl` to the `aiohttp.TCPConnector` constructor. However, the keyword is not valid in the [aiohttp source code](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/connector.py#L716-L729). It looks to me at first glance that the `verify_ssl` keyword argument was changed to just `ssl` but it hasn't been changed in the `aiobotocore` library.

I have not attempted to reproduce this bug myself, but given how straightforward it appears to be, I thought it was worth filing the bug report anyway. If this appears to be something else, then @rickvanhoof may be able to provide context for the failure.

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: 3.8.9
 - OS name and version: Ubuntu 18.04.5

**Additional context**
https://github.com/noahbenson/neuropythy/issues/20

**Comment by thehesiod** [comment] 2021-04-08 03:45
Thanks, will look asap if someone else doesn't get to it before me

**Comment by thehesiod** [comment] 2021-04-09 20:40
going to handle this in https://github.com/aio-libs/aiobotocore/pull/856

**Comment by thehesiod** [comment] 2021-04-09 21:07
`verify_ssl` and `ssl_context` are still valid in the latest release: https://github.com/aio-libs/aiohttp/blob/3.7/aiohttp/connector.py#L740

**Comment by thehesiod** [comment] 2021-04-09 21:26
actually I think this is not a bug, we're using aiohttp 3.7.4.post0 w/ the most recent aiobotocore w/o issue.  I think maybe you were testing with a master release of aiohttp and not official release

**Comment by noahbenson** [comment] 2021-04-09 21:37
I see—the bug report from @rickvanhoof didn't show the aiohttp version so this seems plausible—perhaps he is/was using another library that depended on a non-official version.

 Thanks for looking into this so quickly—if I see any more like this I'll be sure to ask for the `pip freeze`.

**Comment by thehesiod** [comment] 2021-04-09 23:08
closing since we now test with 3.7.4.post0 and it works fine.  Please re-open when you have more information

**Closed by thehesiod** 2021-04-09 23:08 UTC
