### ISSUE TITLE
Timeout on S3 get_object using asyncio.gather

### ISSUE THREAD

**Issue by alliefitter** [aio-libs/aiobotocore#451] opened 2017-11-29 17:15 UTC
I'm attempting to download 300 objects from S3 by building a list of futures and waiting on them to finish with `asyncio.gather`. For some reason, only the ten are finishing and the rest are timing out.

**Code:**
```python
import asyncio

import aiobotocore
from pyboto3 import s3 as s3_client


async def get_logs(s3: s3_client, keys: list = [], token: str = None):
    """

    :param token:
    :type token: str
    :param keys:
    :type keys: list
    :param s3:
    :type s3: s3_client
    :return:
    """
    r = await s3.list_objects_v2(
        Bucket='bucket',
        MaxKeys=1000,
        Prefix='prefix'
    )
    contents = r['Contents'] if 'Contents' in r else []
    is_truncated = r['IsTruncated'] if 'IsTruncated' in r else False
    token = r['NextContinuationToken'] if 'NextContinuationToken' in r else None
    keys = [c['Key'] for c in contents if 'Key' in c] + keys
    print('IsTruncated: {}'.format(is_truncated))
    return keys if not is_truncated else await get_logs(s3, keys, token)


async def get_object(s3: s3_client, key: str):
    """

    :param s3:
    :type s3: s3_client
    :param key:
    :type key: str
    :return:
    """
    print('Downloading {}'.format(key))
    r = await s3.get_object(Bucket='bucket', Key=key)
    print('Finished {}'.format(key))
    return r


async def run(s3: s3_client):
    """

    :param s3:
    :type s3: s3_client
    :return:
    """
    keys = await get_logs(s3)
    r = await asyncio.gather(*[get_object(s3, k) for k in keys])
    print(r)
    return s3.close()


_loop = asyncio.get_event_loop()
_s3 = aiobotocore.get_session(loop=_loop).create_client(
    's3',
    aws_access_key_id='id',
    aws_secret_access_key='key'
)
_loop.run_until_complete(run(_s3))
```
**Output:**
```
IsTruncated: False
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/013d407166ec4fa56eb1e1f8cbe183b9/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/077e29b11be80ab57e1a2ecabb7da330/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/31fefc0e570cb3860f2a6d4b38c6490d/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/82aa4b0af34c2313a562076992e50aa3/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/f899139df5e1059396431415e770c6dd/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/02522a2b2726fb0a03bb19f2d8d9524d/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/07cdfd23373b17c6b337251c22b7ea57/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/3295c76acbf4caaed33c36b1b5fc2cb1/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/839ab46820b524afda05122893c2fe8e/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/f90f2aca5c640289d0a29417bcb63a37/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/07e1cd7dca89a1678042477183b7ac3f/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/32bb90e8976aab5298d5da10fe66f21d/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/84d9ee44e457ddef7f2c4f25dc8fa865/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/fa7cdfad1a5aaf8370ebeda47a1ff1c3/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/084b6fbb10729ed4da8c3d3f5a3ae7c9/000000.gz
Downloading mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/335f5352088d7d9bf74191e006d8e24c/000000.gz

...

Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/013d407166ec4fa56eb1e1f8cbe183b9/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/839ab46820b524afda05122893c2fe8e/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/02522a2b2726fb0a03bb19f2d8d9524d/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/f899139df5e1059396431415e770c6dd/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/07cdfd23373b17c6b337251c22b7ea57/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/077e29b11be80ab57e1a2ecabb7da330/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/f90f2aca5c640289d0a29417bcb63a37/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/3295c76acbf4caaed33c36b1b5fc2cb1/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/31fefc0e570cb3860f2a6d4b38c6490d/000000.gz
Finished mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/82aa4b0af34c2313a562076992e50aa3/000000.gz
Traceback (most recent call last):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/connector.py", line 380, in connect
    yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/allie/PycharmProjects/mdm_reference_architecture/server/tests/logs.py", line 70, in <module>
    _loop.run_until_complete(run(_s3))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/allie/PycharmProjects/mdm_reference_architecture/server/tests/logs.py", line 58, in run
    r = await asyncio.gather(*[get_object(s3, k) for k in ])
  File "/home/allie/PycharmProjects/mdm_reference_architecture/server/tests/logs.py", line 45, in get_object
    r = await s3.get_object(Bucket='logs.cellcontrol-test.com', Key=key)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/client.py", line 80, in _make_api_call
    operation_model, request_dict)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 265, in _send_request
    exception)):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 297, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 321, in _get_response
    request.method, request.url, request.headers, request.body)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 254, in _request
    timeout=None)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/helpers.py", line 99, in __iter__
    ret = yield from self._coro
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/client.py", line 271, in _request
    'to host {0}'.format(url)) from exc
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://s3.amazonaws.com/logs.cellcontrol-test.com/mdm-architecture-reference/server/0f199d90-89fc-4fae-a8ab-f91e39ed3857/812b4ba287f5ee0bc9d43bbf5bbe87fb/000000.gz
```

**Comment by thehesiod** [comment] 2017-11-29 22:11
by default botocore uses a pool of 10 connections, you can increase them by using a `Config` object (See max_pool_connections): https://github.com/boto/botocore/blob/develop/botocore/config.py#L54

however this shouldn't time out.  aiobotocore tries to override the timeout mechanisms of aiohttp because they use a timeout from request start, instead of active time during connect/waiting for response (no one does this, and I had a long and unproductive argument with one of their devs about this)...probably the new version of aiohttp broke something, we'll look into it.

**Comment by alliefitter** [comment] 2017-11-29 22:13
Thanks for the quick response!

**Comment by thehesiod** [comment] 2017-11-29 22:40
btw if you have time let us know if 0.4.x has the issue

**Comment by thehesiod** [comment] 2017-11-30 20:41
somewhat related: https://github.com/aio-libs/aiohttp/issues/2538

**Comment by alliefitter** [comment] 2017-11-30 21:42
```
$ pip freeze
aiobotocore==0.5.1
aiohttp==2.3.3
async-timeout==2.0.0
boto3==1.4.7
botocore==1.7.40
certifi==2017.11.5
chardet==3.0.4
docutils==0.14
idna==2.6
jmespath==0.9.3
multidict==3.3.2
packaging==16.8
pyboto3==1.4.4
pyparsing==2.2.0
python-dateutil==2.6.1
requests==2.18.4
s3transfer==0.1.11
six==1.11.0
urllib3==1.22
wrapt==1.10.11
yarl==0.15.0
```

**Comment by alliefitter** [comment] 2017-12-01 19:08
Got a similar error while trying to create 10,000 SNS topics.

```
Traceback (most recent call last):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/connector.py", line 380, in connect
    yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/allie/PycharmProjects/mdm_reference_architecture/server/tests/init_sns.py", line 40, in <module>
    loop.run_until_complete(init(_client))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/allie/PycharmProjects/mdm_reference_architecture/server/tests/init_sns.py", line 30, in init
    await asyncio.gather(*[create_topic(sns, 'mdm-phone-incoming-{}'.format(line['udid'])) for line in reader])
  File "/home/allie/PycharmProjects/mdm_reference_architecture/server/tests/init_sns.py", line 18, in create_topic
    await sns.create_topic(Name=name)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/client.py", line 80, in _make_api_call
    operation_model, request_dict)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 265, in _send_request
    exception)):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 297, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 321, in _get_response
    request.method, request.url, request.headers, request.body)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiobotocore/endpoint.py", line 254, in _request
    timeout=None)
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/helpers.py", line 99, in __iter__
    ret = yield from self._coro
  File "/home/allie/virtualenvs/mdm_architecture_reference_server/lib/python3.6/site-packages/aiohttp/client.py", line 271, in _request
    'to host {0}'.format(url)) from exc
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host https://sns.us-east-1.amazonaws.com/
```

**Comment by alliefitter** [comment] 2017-12-01 19:11
It did end up creating 8202 of the topics.

**Comment by thehesiod** [comment] 2017-12-01 19:26
can you try aiobotocore 0.4.x

**Comment by thehesiod** [comment] 2018-01-09 21:03
@alliefitter note: that if AWS does not receive a message w/in 15 seconds or so it will timeout the connection.  So if your cpu usage was too high it can cause starvation.  Another is that you're not reading the body of the S3 object so you're going to cause the connectors to be reset after every API call (inefficient).  However `async_timeout` should never be used so something has gone wrong when aiobotocore was updated recently to use the new aiohttp client.  I'll investigate.

**Comment by thehesiod** [comment] 2018-01-09 21:18
actually the issue is due to https://github.com/aio-libs/aiohttp/issues/2648.  I'll work on a work-around

**Comment by thehesiod** [comment] 2018-02-23 18:19
ok 0.5.3 released with my connector timeout fix, re-open if this does not solve your issue.

**Closed by thehesiod** 2018-02-23 18:19 UTC

**Comment by dmvieira** [comment] 2020-07-08 15:08
I'm getting the same ServerTimeoutError on version 1.0.4. It's using DynamoDB getting this error with some requests. The requests take more than 1 second (I think that is about retry), but returns this aiohttp error. I'm using retry mode "standard". Here the traceback:

```
File "/usr/local/lib/python3.7/site-packages/aioboto3/resources/factory.py", line 239, in do_action
response = await action(self, *args, **kwargs)

File "/usr/local/lib/python3.7/site-packages/aioboto3/resources/action.py", line 41, in __call__
response = await getattr(parent.meta.client, operation_name)(**params)

File "/usr/local/lib/python3.7/site-packages/aiobotocore/client.py", line 112, in _make_api_call
operation_model, request_dict, request_context)

File "/usr/local/lib/python3.7/site-packages/aiobotocore/client.py", line 131, in _make_request
return await self._endpoint.make_request(operation_model, request_dict)

File "/usr/local/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 109, in _send_request
raise exception

File "/usr/local/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 155, in _do_get_response
http_response = await self._send(request)

File "/usr/local/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 236, in _send
request.method, url=url, headers=headers_, data=data, proxy=proxy)

File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
await resp.start(conn)

File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
message, payload = await self._protocol.read()  # type: ignore  # noqa

File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
await self._waiter
```

Here my configuration:

```
        config = AioConfig(
            connect_timeout=0.01
            read_timeout=0.05,
            retries={
                "total_max_attempts": 3,
                "mode": "standard"
            },
        )
```

**Comment by thehesiod** [comment] 2020-07-08 23:38
hmm, need testcase.  Can you open new bug with testcase and setup info
